### ISSUE TITLE
Hi, please add documentation on how to use this plugin

### ISSUE THREAD

**Issue by Amaratsu** [FrozenStormInteractive/Unreal-SignalR#1]

**Comment by EhmedBelal** [comment]
Download the source code and manually paste the folder here drive:\Program Files\Epic Games\UE_4.XXX\Engine\Plugins\Marketplace\
Then launch the project and enable the plugin.

**Comment by Amaratsu** [comment]
I propose to put the plugin on the platform https://www.unrealengine.com/marketplace/en-US/store and support the plugin, I will buy it one of the first

**Comment by AlfieAllen** [comment]
Are this plugin use https://github.com/aspnet/SignalR-Client-Cpp official library?

**Comment by Amaratsu** [comment]
> 

Yes

**Comment by Amaratsu** [comment]
> Are this plugin use https://github.com/aspnet/SignalR-Client-Cpp official library?

Yes, do you want to use it or make your own version?

**Comment by AlfieAllen** [comment]
What r u mean about use? This plugin or signalR official library?
Yes, I want to use this plugin

**Comment by Amaratsu** [comment]
> 



> What r u mean about use? This plugin or signalR official library?
> Yes, I want to use this plugin

I thought you might want to make a plugin with output to blueprints

**Comment by AlfieAllen** [comment]
> I thought you might want to make a plugin with output to blueprints

Yes, I want :)

**Comment by Amaratsu** [comment]
> > I thought you might want to make a plugin with output to blueprints
> 
> Yes, I want :)

If you can do it, put it on the market, I'm really looking forward to this plugin, because I'm not strong in C ++

**Comment by AlfieAllen** [comment]
> If you can do it, put it on the market, I'm really looking forward to this plugin, because I'm not strong in C ++

I think plugin owner will add it to the market.

**Comment by intelligide** [comment]
Hello and sorry for not answering more quickly, I am quite busy. I started working on it again by fixing some bugs and improving the usability, I also added some docs (I am definitely bad at writing good documentation, sorry :sweat_smile:)

This plugin does'nt use https://github.com/aspnet/SignalR-Client-Cpp, It is only based on it. This is to avoid using heavy and complicated libraries that are not compatible with non-public platforms like consoles. (SignalR-Client-Cpp uses cpprestsdk and jsoncpp)

I don't think I will put this plugin on the marketplace for several reasons:
- I want to be free in my development and not meet the quality requirements of any store.
- It requires too much time to maintain and update versions and various administrative tasks.
- I'm not sure to maintain constant support on it, so I feel bad to make people pay for something without support.
- I don't need money (I already have a full time job).

**Comment by AlfieAllen** [comment]
> This plugin does'nt use https://github.com/aspnet/SignalR-Client-Cpp, It is only based on it. This is to avoid using heavy and complicated libraries that are not compatible with non-public platforms like consoles.

I want to say, that this SignalR protocol needs to communicate between dedicated server and backend servers, not between clients and unreal dedicated servers. We have native RPC events, the native Online beacons and great REST VaRest plugin for this purposes. 

And using official https://github.com/aspnet/SignalR-Client-Cpp library made u free from 90% developing, you needs just to wrap it into ue plugin at all.
