### ISSUE TITLE
 I can't receive messages

### ISSUE THREAD

**Issue by alespin2021** [FrozenStormInteractive/Unreal-SignalR#7]
I follow the instructions (unreal 4.27), get connected and send messages to the signalr server... but I can't receive message from the server.

    Hub = GEngine->GetEngineSubsystem<USignalRSubsystem>()>CreateHubConnection("http://localhost:5084/echoHub");

    Hub->On(TEXT("Say")).BindLambda([](const TArray<FSignalRValue>& Arguments) {
        UE_LOG(LogTemp, Warning, TEXT("Message received"));
        });

    Hub->OnConnected().AddLambda([this]{
        UE_LOG(LogTemp, Warning, TEXT("Connected"));
    });

    Hub->OnConnectionError().AddLambda([](const FString Message) {
        UE_LOG(LogTemp, Warning, TEXT("Error: %s"), *Message);
     });

    Hub->Start();

I will like to know at least where to debug... because Im not getting anything

**Comment by alespin2021** [comment]
my bad... its ok now

**Comment by sebamateja** [comment]
@alespin2021 Hello, could you maybe specify what was your issue and how you fixed it?
